### PR TITLE
feat(card): replace cards of libraries, news & posts by Material UI / Material Kit Card

### PR DESCRIPTION
**Pull request by csouchet**
image
image
image
image

Covers #831

### CODE REVIEW

**Comment by tbouffard** [comment]
✔️ I really like the new cards layout

❓ the title in the cards of the library are capitalized. Is it possible to avoid that because it displays the wrong name capitalization of library name
Bpmn-visualization instead of bpmn-visualization, BpmnVisualizationR instead of bpmnVisualizationR, MxGraph instead of mxGraph, ....

image

**Comment by csouchet** [comment]
Now, unlike before, all images in the map have the same size. What's more, thanks to the use of a specific CSS configuration (object-fit: 'cover'), the browser fills the entire image area, even if this means cutting off part of the image if it doesn't fit.

**Comment by csouchet** [comment]
@tbouffard   
I have made the following changes:  
\- Fixed the titles on the library cards.  
\- Changed the hover effect on the cards to fix the problem with the shadow (it wasn't possible to translate it easily).  
\- Adjusted the z-index of the header. The z-index of the card images was already set to 1.

**Review by tbouffard — APPROVED** [review]
Checked with the live preview. I didn't check the code at all.

> \- Fixed the titles on the library cards.  

OK

> \- Changed the hover effect on the cards to fix the problem with the shadow (it wasn't possible to translate it easily).  

Nice. No need to translate, that's pretty good like this.

cards_hover_v2


> \- Adjusted the z-index of the header. The z-index of the card images was already set to 1.

OK, fine. Tested on the home page and other pages.

> Now, unlike before, all images in the card have the same size. 

Let keep the rendering of the images as they are now. As discussed together, the images from unslpash have the right ratio, the issue is with screenshot we took or images taken from external site (Hacktoberfest for instance).
We will have to be careful to use a consistent ratio in the future.

**Pull request merged**
