### PR TITLE
[FEAT] Change footer

### LINKED ISSUE #636: [FEAT] Replace the existing footer by a new footer with all pages
Like https://demos.creative-tim.com/material-kit-react/#/pages/landing-pages/contact-us

Make with `Material UI KIT` (keep `style-component` for the rest)

### PR DESCRIPTION
**Pull request by csouchet**
- Add new dependencies for Material UI
- Add 2 different kinds of footer to choose -> We choose the first with the list of all pages

Closes #636 

### Material UI
The doc pages useful for our implementation:
- https://mui.com/material-ui/customization/breakpoints/
- https://mui.com/material-ui/customization/typography/
- https://mui.com/material-ui/customization/palette/
- https://mui.com/material-ui/customization/theming/
- https://mui.com/material-ui/customization/default-theme/
- https://mui.com/material-ui/customization/color/
- https://mui.com/material-ui/api/container/
- https://mui.com/material-ui/material-icons/

### CODE REVIEW

**Comment by csouchet** [comment]
image

**Comment by csouchet** [comment]
We choose to keep the first, with the list of all pages.

**Comment by csouchet** [comment]
### Desktop version
image

### Mobile version
#### iPhone 11 Pro
image
#### Galaxy Note 20
image

**Review by tbouffard — CHANGES_REQUESTED** [review]
I was expected changes in the footer only, but I see that all pages have been moved and there are problems. The moved pages include "blog", "news", model-generation-application' 
- home: the "see all" and "model generation app" buttons go to old pages --> 404 error
- missing redirections from old pages to new pages. This is mandatory for SEO and users that have bookmark pages
- the link in the footer in non home page are wrong and leads to 404 error pages. They are relative to the current page. For instance, in the 'model-generation-application' page, the news page link is https://process-analytics-process-analytics-dev-site_preview-pr-604.surge.sh/components/model-generation-application/learn/news

If possible, restore the existing url and manage the page location change in another PR. This would limit the things to review.

About the footer itself. I will review the whole things later
- why using the "legacy" wording in the "help & legacy" menu? can we rename it to "help"

**Comment by csouchet** [comment]
> I was expected changes in the footer only, but I see that all pages have been moved and there are problems. The moved pages include "blog", "news", model-generation-application'
> 
>     * home: the "see all" and "model generation app" buttons go to old pages --> 404 error
> 
>     * missing redirections from old pages to new pages. This is mandatory for SEO and users that have bookmark pages
> 
>     * the link in the footer in non home page are wrong and leads to 404 error pages. They are relative to the current page. For instance, in the 'model-generation-application' page, the news page link is https://process-analytics-process-analytics-dev-site_preview-pr-604.surge.sh/components/model-generation-application/learn/news
> 
> 
> If possible, restore the existing url and manage the page location change in another PR. This would limit the things to review.
> 
> About the footer itself. I will review the whole things later
> 
>     * why using the "legacy" wording in the "help & legacy" menu? can we rename it to "help"

Ok for change the page tree in another PR (It was a test for generate dynamically the footer routes).

For the wording "legacy", it's a mistake. The real word is "Legal". 
I was inspired by https://demos.creative-tim.com/material-kit-pro-react/#/sections/page-sections/footers.

**Comment by tbouffard** [comment]
### No more "link highlight" in the footer

It is hard to see that there are links in the footer

**Previous behavior**

https://user-images.githubusercontent.com/27200110/186162710-2c28532b-4b25-45d6-92c9-2bdd2522e78b.mp4

**Proposed changes**

https://user-images.githubusercontent.com/27200110/186162721-c763292d-2874-4502-85ea-2b9193577a67.mp4


### Others

In the Help&Legal column, the "Usage conditions of Model Generation Application" title is too long: can we change it to `Terms of Use` (that will be the final name)?

I sometimes see a react error in the devtools console
```
react-dom.production.min.js:293 Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at xi (react-dom.production.min.js:293:39)
    at bs (react-dom.production.min.js:280:389)
    at gs (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
    at as (react-dom.production.min.js:271:88)
    at ls (react-dom.production.min.js:268:429)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
```

**Comment by tbouffard** [comment]
✔️ with commit db53010

large | medium | small
---- | ---- | ----
image | image | image

**Review by tbouffard — APPROVED** [review]
LGTM

**Pull request merged**
